# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171013_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='200px', null=True, upload_to='', width_field='200px'),
        ),
    ]
